name: pipelineDemo__$(Date:yyyyMMdd) --> $(Rev:r)

trigger:
- main

pool: agellenVmssGradle01

stages:
  - stage: Stage_1
    jobs:
    - job: Job_1
      steps:
        - template: template1.yml

    - job: Job_2
      steps:
      - script: echo hello stage1, job2
      displayName: 'Stage 1, Job 2'
  
  - stage: Stage_2
    jobs:
    - job: Job_3
      steps:
      - script: echo hello stage2, job3
      displayName: 'Stage 2, Job 3'
    
    - job: Job_4
      steps:
        - template: template2.yml